### ISSUE TITLE
[BUG] - Sidebar / Toolbar

### ISSUE THREAD

**Issue by virgo77** [linuxserver/docker-keepassxc#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi there,
as you implemented it in the Docker Container, and as I don't know if this bug is for you, or for the original devs... anyways, it's about KasmVNC and its useful sidebar/toolbar

When I move this sidebar on the right of the screen, the little anchored arrow is not well-positioned, as you can see on these screenshots:
![image](https://github.com/linuxserver/docker-keepassxc/assets/23108339/545c8598-28e9-457d-8482-5c794cbd6c23)
![image](https://github.com/linuxserver/docker-keepassxc/assets/23108339/d8f63b84-7edb-49b9-83e9-46dcf9bf4a12)

Is it up to you, or may I have to open an issue topic on the KasmVNC GitHub board?

Thanks a lot

V.

### Steps To Reproduce

none specific. Just take a look at the screenshots :)

### Environment

```markdown
- OS: Ubuntu Server 22.04.4
- Docker: 26.0.1
- Portainer: 2.19.5

> How docker service was installed?
I followed this tuto = https://i12bretro.github.io/tutorials/0779.html

# update software repositories
	sudo apt update
	
# install prerequisites
	sudo apt install curl apt-transport-https ca-certificates curl software-properties-common gnupg-agent -y

# add docker gpg key
	curl -fsSL https://download.docker.com/linux/$(awk -F'=' '/^ID=/{ print $NF }' /etc/os-release)/gpg | sudo apt-key add -

# add docker software repository
	sudo add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/$(awk -F'=' '/^ID=/{ print $NF }' /etc/os-release) $(lsb_release -cs) stable"

# install docker
	sudo apt install docker-ce docker-compose containerd.io -y

# enable and start docker service
	sudo systemctl enable docker && sudo systemctl start docker

# add the current user to the docker group
	sudo usermod -aG docker $USER
```

### CPU architecture

x86-64

### Docker creation

```bash
1. I created a custom volume:
`docker volume create --driver local \
    --opt type=none \
    --opt device=/home/docker/volumes/data \
    --opt o=bind vol_data`

2. Then I installed KeePassXC:
`docker pull lscr.io/linuxserver/keepassxc:latest`
`docker run -d --name KeepassXC --restart unless-stopped -e TZ=Europe/Paris -p 3000:3000 -p 3001:3001 -v vol_data:/data lscr.io/linuxserver/keepassxc:latest`

3. Access via the IP:3000 and so go on!
```

### Container logs

```bash
no logs, it's working like a charm
```

**Comment by thelamer** [comment]
This is kind of outside of my wheelhouse, you could file an issue here: 

https://github.com/kasmtech/novnc
